apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-stilling-indekser
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-stilling-indekser
      rules:
        - alert: rekrutteringsbistand-stilling-indekser
          expr: sum(up{app="rekrutteringsbistand-stilling-indekser", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/CuggT"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stilling-indekser
          expr: sum(increase(logd_messages_total{log_app="rekrutteringsbistand-stilling-indekser",log_level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/CuggT"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-stilling-indekser
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-stilling-indekser  ",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-stilling-indekser  "}[5m]))) > 5
          for: 3m
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/CuggT"
          labels:
            namespace: toi
            severity: warning
