apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-indekser
  namespace: toi
  labels:
    team: toi
spec:
  image: {{image}}
  port: 8222
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: rekrutteringsbistand-stilling-api
  openSearch:
    access: admin
    instance: rekrutteringsbistand-stilling
  envFrom:
    - secret: rekrutteringsbistand-stilling-indekser-servicebruker
  env:
    - name: REKRUTTERINGSBISTAND_STILLING_API_URL
      value: http://rekrutteringsbistand-stilling-api
    - name: INDEKS_VERSJON
      value: {{indeks_versjon}}
  kafka:
    pool: {{kafka_pool}}
