apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-indekser
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8222
  ingresses:
  {{#each ingress as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      external:
        - host: {{outbound}}
