apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-stilling-indekser
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  port: 8222
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{rekrutteringsbistand-stilling-api-host}}
        - host: {{elasticsearch-host}}
  elastic:
    instance: rekrutteringsbistand-stilling
  envFrom:
    - secret: rekrutteringsbistand-stilling-indekser-es-credentials
    - secret: rekrutteringsbistand-stilling-indekser-servicebruker
  env:
    - name: REKRUTTERINGSBISTAND_STILLING_API_URL
      value: https://{{rekrutteringsbistand-stilling-api-host}}
    - name: ELASTIC_SEARCH_API
      value: https://{{elasticsearch-api}}
    - name: INDEKS_VERSJON
      value: "16"
  kafka:
    pool: {{kafka_pool}}
